apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: staging-prod-deploy
profiles:
  - name: staging
    deploy:
      kubeContext: gke_fz-prod-01_asia-south1_gke-fz-prod-as1-01
      kubectl:
        manifests:
          - k8/deployment.yaml
          - k8/service.yaml
