apiVersion: apps/v1
kind: Deployment
metadata:
  name: "todo-app"
spec:
  replicas: "2"
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: null
    spec:
      containers:
        - name: todo-app
          image: "gcr.io/tech-rnd-project/todo"
          ports:
            - containerPort: 3000
